server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://应用数据库地址:应用数据库端口/应用数据库名称?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: 应用数据库账户
    password: 应用数据库密码
  redis:
    host: 192.168.1.233
    port: 6543
    password: yMxsueZD9yx0AkfR
    database: 0
    timeout: 10s

logging:
  level:
    root: info



mqtt:
  #  emq 服务地址
  host: tcp://192.168.1.244:1883
  #  emq 用户名
  username: admin
  #   emq 密码
  password: 1234abc
  #   客户端标识
  clientId: core
  # post url
  publish_url: http://192.168.1.244:8080/api/v3/mqtt/publish
  app_id: 536c0891820c
  app_key: Mjg4Mjc0NTc5MDM5ODMzMDM5NDk0NjY1NzI3MjY2NjUyMTG